services:
  - type: web
    name: laravel
    env: php
    buildCommand: composer install --no-interaction --prefer-dist
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
